# Generated by Django 2.2.2 on 2019-07-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0002_auto_20190702_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imageFile',
        ),
        migrations.AddField(
            model_name='product',
            name='imageURL',
            field=models.CharField(db_column='image_url', default='', max_length=1024),
        ),
    ]
