# Generated by Django 2.2.5 on 2019-09-23 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0003_auto_20190704_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã nhóm sản phẩm')),
                ('name', models.CharField(max_length=50, verbose_name='Tên nhóm sản phẩm')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='freeShip',
            field=models.BooleanField(db_column='free_ship', default=False, verbose_name='Miễn phí vận chuyển'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Category'),
        ),
    ]
